name: Build

on:
  workflow_dispatch:
    inputs:
      codec:
        description: '声卡型号 (例如: ALC897)'
        required: true
        type: string
        default: 'ALC897'

jobs:
  build:
    name: Build AppleALC
    runs-on:
      - macos-latest
    steps:
      - name: Checkout to current repo
        uses: actions/checkout@v3
      - name: Create output directory for built kexts
        run: mkdir -p Kexts
      - name: Clone AppleALC from source
        run: git clone https://github.com/acidanthera/AppleALC
      - name: Get AppleALC latest stable release
        id: applealc-latest-release
        working-directory: AppleALC
        run: echo "::set-output name=tag-name::$(git describe --tags `git rev-list --tags --max-count=1`)"
      - name: Checkout to AppleALC latest stable release
        working-directory: AppleALC
        run: git checkout ${{ steps.applealc-latest-release.outputs.tag-name }}
      - name: Remove compressed kern_resources.cpp
        working-directory: AppleALC
        run: "[ ! -e AppleALC/kern_resources.cpp ] && rm -rf AppleALC/kern_resources.cpp"
      - name: Clone MacKernelSDK from source
        working-directory: AppleALC
        run: |
          echo "WARNING: MacKernelSDK doesn't appear to be cloned. Cloning...;"
          git clone https://github.com/acidanthera/MacKernelSDK.git
      - name: Build Lilu DEBUG from bootstrap.sh
        working-directory: AppleALC
        run: |
          echo "WARNING: Lilu debug doesn't appear to be there. Building...";
          wget https://raw.githubusercontent.com/acidanthera/Lilu/master/Lilu/Scripts/bootstrap.sh  > /dev/null 2>&1
          bash bootstrap.sh
      - name: Create a temp folder
        working-directory: AppleALC
        run: |
          mv Resources Resources_bak
          mkdir Resources
          mv Resources_bak/PinConfigs.kext Resources
          mv Resources_bak/Controllers.plist Resources
          mv Resources_bak/Kexts.plist Resources
          mv Resources_bak/Vendors.plist Resources
          
          # 检查指定的codec是否存在
          if [ ! -d "Resources_bak/${{ inputs.codec }}" ]; then
            echo "Error: Codec ${{ inputs.codec }} not found!"
            exit 1
          fi
          
          # 复制指定设备的所有文件
          mkdir -p Resources/${{ inputs.codec }}
          cp -r Resources_bak/${{ inputs.codec }}/* Resources/${{ inputs.codec }}/

      - name: Build AppleALC
        working-directory: AppleALC
        run: |
          xcodebuild -quiet -project AppleALC.xcodeproj -scheme AppleALC -configuration Release -sdk macosx -derivedDataPath out 
          mv out/Build/Products/Release/*.zip ../Kexts/${{ inputs.codec }}.zip
          rm -rf out

      - name: Upload to artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.codec }}
          path: Kexts/*
      - name: Upload to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Kexts/*.zip
          tag: ${{ github.ref }}
          file_glob: true

