name: CI

on:
  push:
    branches: [master]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  ocvalidate:
    name: "Build slimmed AppleALC"
    uses: ./.github/workflows/build.yml
  generate-docs:
    name: "Generate Docs"
    uses: ./.github/workflows/docs.yml
